---
  - name: Install and launch Metricbeat
    hosts: webservers
    become: true
    tasks:

    - name: Download metric beat .deb file
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: Install Metricbeat .deb
      command: dpkg -i metricbeat-7.6.1-amd64.deb

    - name: Copy metricbeat-config.yml to /etc/metricbeat/metricbeat.yml
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable and configure docker module for metricbeat
      command: metricbeat modules enable docker

    - name: Setup metric beat
      command: metricbeat setup

    - name: Start metricbeat services
      command: service metricbeat start

    - name: Enable service metricbeat on boot
      systemd:
        name: metricbeat
        enabled: yes